<?php

define('APIOM_ACCOUNTS_INDEX_PREFIX', 'accdev_');
define('APIOM_ACCOUNTS_MESSAGE_QUEUE_NAME', 'accounts-dev');

$conf = array_merge((array) $conf, [
    # URL of internal services
    # ---------------------
    'apiom_accounts_api_server'                => 'http://web',
    'uptime_url'                               => 'http://web/GO1/uptime-service',
    'queue_url'                                => 'http://web/GO1/queue-service',
    'user_url'                                 => 'http://web/GO1/user-service',
    'mail_url'                                 => 'http://web/GO1/mail-service',
    'entity_url'                               => 'http://web/GO1/entity-service',
    'payment_url'                              => 'http://web/GO1/payment-service',

    # disable launching new site.
    # ---------------------
    'apiom_accounts_onboarding_queue_enable'   => true,

    # Stripe
    # ---------------------
    'apiom_accounts_payment_stripe_secret_key' => 'sk_test_Mn5hUz1xtvWXQdwg2vi4hykG',
    'apiom_accounts_payment_stripe_public_key' => 'pk_test_s9dJH7JI5nEJ6mM9bF4bFSCW',
    'apiom_accounts_payment_stripe_client_id'  => 'ca_7Miz7kOSIbqSIZbSrr3dftHnlCFkSRpt',

    # QA portals, the data generated by these portals will be deleted.
    # ---------------------
    'accounts_qa_instances'                    => [
        'deva.mygo1.com',
        'devb.mygo1.com',
    ],

    # Workers — ps auxf | grep accounts-dev | grep worker | grep root
    # ---------------------
    'accounts_has_cache_worker'                => true,
    'accounts_has_pull_worker'                 => true,

    # Send notify to rabbitmq
    # ---------------------
    'apiom_accounts_send_notify'               => true,
]);

// Display errors if ?debug=1
if (!empty($_GET['debug'])) {
    error_reporting(E_ALL);
    $conf['error_level'] = 2;
    ini_set('display_errors', true);
    ini_set('display_startup_errors', true);
}

if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS'])) {
    header('Access-Control-Allow-Headers: ' . $_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']);
}
