<?php

return [
    'php'            => [
        'algolia'      => 'git@code.go1.com.au:microservices/algolia.git',
        'api'          => 'git@code.go1.com.au:microservices/api.git',
        'assessor'     => 'git@code.go1.com.au:microservices/assessor.git',
        'assignment'   => 'git@code.go1.com.au:microservices/assignment.git',
        'batch'        => 'git@code.go1.com.au:microservices/batch.git',
        'cloudinary'   => 'git@code.go1.com.au:microservices/cloudinary.git',
        'console'      => 'git@code.go1.com.au:go1/console.git',
        'credit'       => 'git@code.go1.com.au:microservices/credit.git',
        'currency'     => 'git@code.go1.com.au:microservices/currency.git',
        'eck'          => 'git@code.go1.com.au:microservices/eck.git',
        'endpoint'     => 'git@code.go1.com.au:microservices/endpoint.git',
        'enrolment'    => 'git@code.go1.com.au:microservices/enrolment.git',
        'entity'       => 'git@code.go1.com.au:microservices/entity.git',
        'finder'       => 'git@code.go1.com.au:microservices/finder.git',
        'graphin'      => 'git@code.go1.com.au:microservices/graphin.git',
        'history'      => 'git@code.go1.com.au:microservices/history.git',
        'index'        => 'git@code.go1.com.au:microservices/index.git',
        'lib'          => 'git@code.go1.com.au:microservices/lib.git',
        'lo'           => 'git@code.go1.com.au:microservices/lo.git',
        'lob'          => 'git@code.go1.com.au:microservices/lob.git',
        'low'          => 'git@code.go1.com.au:microservices/low.git',
        'lti-consumer' => 'git@code.go1.com.au:microservices/lti-consumer.git',
        'mail'         => 'git@code.go1.com.au:microservices/mail.git',
        'natero'       => 'git@code.go1.com.au:microservices/natero.git',
        'note'         => 'git@code.go1.com.au:microservices/note.git',
        'notify'       => 'git@code.go1.com.au:microservices/notify.git',
        'onboard'      => 'git@code.go1.com.au:microservices/onboard.git',
        'payment'      => 'git@code.go1.com.au:microservices/payment.git',
        'portal'       => 'git@code.go1.com.au:microservices/portal.git',
        'queue'        => 'git@code.go1.com.au:microservices/queue.git',
        'quiz'         => 'git@code.go1.com.au:microservices/quiz.git',
        'report-data'  => 'git@code.go1.com.au:microservices/report-data.git',
        'report'       => 'git@code.go1.com.au:microservices/report.git',
        'rules'        => 'git@code.go1.com.au:microservices/rules.git',
        's3'           => 'git@code.go1.com.au:microservices/s3.git',
        'scraping'     => 'git@code.go1.com.au:microservices/scraping.git',
        'sms'          => 'git@code.go1.com.au:microservices/sms.git',
        'social'       => 'git@code.go1.com.au:microservices/social.git',
        'sso'          => 'git@code.go1.com.au:microservices/sso.git',
        'staff'        => 'git@code.go1.com.au:microservices/staff.git',
        'stash'        => 'git@code.go1.com.au:microservices/stash.git',
        'status'       => 'git@code.go1.com.au:microservices/status.git',
        'subscription' => 'git@code.go1.com.au:microservices/subscription.git',
        'user'         => 'git@code.go1.com.au:microservices/user.git',
        'video'        => 'git@code.go1.com.au:microservices/video.git',
        'vote'         => 'git@code.go1.com.au:microservices/vote.git',
        # 'uptime'       => 'git@code.go1.com.au:microservices/uptime.git',
        # 'workshop'     => 'git@code.go1.com.au:microservices/workshop.git',
    ],
    'php/libraries'  => [
        'app'            => 'git@github.com:go1com/app.git',
        'clients'        => 'git@code.go1.com.au:go1/clients.git',
        'edge'           => 'git@github.com:go1com/edge.git',
        'flood'          => 'git@github.com:go1com/flood.git',
        'jwt_middleware' => 'git@github.com:go1com/JwtMiddleware.git',
        'kv'             => 'git@github.com:go1com/kv.git',
        'middleware'     => 'git@code.go1.com.au:go1/middlewares.git',
        'schema'         => 'git@code.go1.com.au:go1/schema.git',
        'util'           => 'git@code.go1.com.au:go1/util.git',
        'graph_mock'     => 'git@code.go1.com.au:go1/graph-mock.git',
        'report_helpers' => 'git@code.go1.com.au:go1/report-helpers.git',
    ],
    'drupal'         => [
        'accounts' => 'git@code.go1.com.au:go1/accounts.git',
        'gc'       => 'git@code.go1.com.au:gc/gocatalyze.git',
    ],
    'golang'         => [
        // Please update build-go.php
        // The projects are managed by glide.
    ],
    'web'            => [
        'ui'      => 'git@code.go1.com.au:apiom/apiom-ui.git',
        'website' => 'git@code.go1.com.au:web/go1web.git',
    ],
    'infrastructure' => [
        'cron'          => 'git@code.go1.com.au:microservices/cron.git',
        'deploy_helper' => 'git@github.com:go1com/deploy_helper.git',
        'ecs'           => 'git@code.go1.com.au:go1/launch-configuration.git',
        'goweb'         => 'git@code.go1.com.au:microservices/goweb.git',
        'haproxy'       => 'git@code.go1.com.au:go1/haproxy.git',
        'memcached'     => 'git@code.go1.com.au:server/memcached.git',
        'docker-php'    => 'https://github.com/go1com/docker-php.git',
        'wait-for-it'   => 'https://github.com/vishnubob/wait-for-it.git',
    ],
    'nodejs'         => [
        # 'algolia' => 'git@code.go1.com.au:microservices/algolia.git',
        'report' => 'git@code.go1.com.au:microservices/report-index.git',
        # @TODO: realtime
    ],
];
